import FinanceCoreSDK

extension TransactionDTO {
    public func toDomain() -> Transaction {
        Transaction(
            lunchMoneyId: id,
            date: date,
            payee: payee,
            amount: amount,
            currency: currency,
            toBase: toBase,
            notes: notes,
            originalName: originalName,
            categoryId: categoryId,
            categoryName: categoryName,
            categoryGroupId: categoryGroupId,
            categoryGroupName: categoryGroupName,
            status: status,
            isIncome: isIncome,
            isPending: isPending,
            excludeFromBudget: excludeFromBudget,
            excludeFromTotals: excludeFromTotals,
            createdAt: createdAt,
            updatedAt: updatedAt,
            recurringId: recurringId,
            recurringPayee: recurringPayee,
            recurringDescription: recurringDescription,
            recurringCadence: recurringCadence,
            recurringGranularity: recurringGranularity,
            recurringQuantity: recurringQuantity,
            recurringType: recurringType,
            recurringAmount: recurringAmount,
            recurringCurrency: recurringCurrency,
            parentId: parentId,
            hasChildren: hasChildren,
            groupId: groupId,
            isGroup: isGroup,
            assetId: assetId,
            assetInstitutionName: assetInstitutionName,
            assetName: assetName,
            assetDisplayName: assetDisplayName,
            assetStatus: assetStatus,
            plaidAccountId: plaidAccountId,
            plaidAccountName: plaidAccountName,
            plaidAccountMask: plaidAccountMask,
            institutionName: institutionName,
            plaidAccountDisplayName: plaidAccountDisplayName,
            plaidMetadata: plaidMetadata,
            source: source,
            displayName: displayName,
            displayNotes: displayNotes,
            accountDisplayName: accountDisplayName,
            externalId: externalId,
            tags: (tags ?? []).map { Tag(lunchMoneyId: $0.id, name: $0.name) }
        )
    }
}
