name: Dev Deploy

on:
  push:
    branches:
      - "main"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
  repository-projects: read

jobs:
  deploy:
    name: Dev Deploy
    uses: ./.github/workflows/deploy.yml
    with:
      awsRegion: us-east-1
      environment: dev
      dockerPlatformName: linux/amd64
      productName: LambdaApp
    secrets: inherit
